"""Audit-log module: JSONL writer + reader + hash chain + signatures + attestor. SPEC §2."""

from .attestor import (
    ATTESTATION_PAYLOAD_VERSION,
    AttestationPayload,
    AttestationReceipt,
    Attestor,
    HttpAttestorError,
    HttpAttestorOptions,
    http_attestor,
    null_attestor,
    payload_from_record,
)
from .correlation import (
    ArgsHash,
    AuditSource,
    CorrelationMatch,
    CorrelationOptions,
    SessionSummary,
    correlate,
    find_args_hash_collisions,
    find_overlapping_sessions,
    find_sequence_similarity,
    hash_args,
    summarize_sessions,
)
from .stats import (
    PROFILE_SCHEMA_VERSION,
    AgentProfile,
    CompareOptions,
    Deviation,
    DeviationReport,
    analyze_agent,
    analyze_multi_agent,
    compare_to_baseline,
    mean,
    stddev,
)
from .chain import (
    GENESIS_HASH,
    canonical_json_string,
    canonicalize_for_hash,
    compute_record_hash,
)
from .reader import AuditLogReader
from .signature import (
    SIGNATURE_PREFIX,
    generate_ed25519_keypair,
    load_private_key,
    load_public_key,
    sign_record,
    verify_record,
)
from .writer import AuditLogWriter, AuditLogWriterOptions

__all__ = [
    "ATTESTATION_PAYLOAD_VERSION",
    "AgentProfile",
    "ArgsHash",
    "AttestationPayload",
    "AttestationReceipt",
    "Attestor",
    "AuditLogReader",
    "AuditLogWriter",
    "AuditLogWriterOptions",
    "AuditSource",
    "CompareOptions",
    "CorrelationMatch",
    "CorrelationOptions",
    "Deviation",
    "DeviationReport",
    "GENESIS_HASH",
    "HttpAttestorError",
    "HttpAttestorOptions",
    "PROFILE_SCHEMA_VERSION",
    "SIGNATURE_PREFIX",
    "SessionSummary",
    "analyze_agent",
    "analyze_multi_agent",
    "canonical_json_string",
    "canonicalize_for_hash",
    "compare_to_baseline",
    "compute_record_hash",
    "correlate",
    "find_args_hash_collisions",
    "find_overlapping_sessions",
    "find_sequence_similarity",
    "generate_ed25519_keypair",
    "hash_args",
    "http_attestor",
    "load_private_key",
    "load_public_key",
    "mean",
    "null_attestor",
    "payload_from_record",
    "sign_record",
    "stddev",
    "summarize_sessions",
    "verify_record",
]
