"""ed25519 signatures for audit-log records. SPEC §2.6.

The signature is computed over the canonical bytes of the record with
`signature` stripped (matches `canonicalize_for_hash`). Wire format is
`ed25519:<base64url>` — base64url WITHOUT padding, byte-identical to the
TypeScript reference impl.

Key files use PKCS#8 PEM for private keys and SPKI PEM for public keys —
the default formats produced by Node's `crypto.generateKeyPairSync('ed25519')`,
so a key generated by either implementation is loadable by the other.
"""

from __future__ import annotations

import base64
from typing import Tuple, Union

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.exceptions import InvalidSignature

from ..types import AuditRecord
from .chain import canonicalize_for_hash

SIGNATURE_PREFIX = "ed25519:"


def generate_ed25519_keypair() -> Tuple[bytes, bytes]:
    """Generate a fresh ed25519 key pair as (private_pem, public_pem) bytes.

    Private key is PKCS#8 PEM (unencrypted). Public key is SPKI PEM. Both
    are interchangeable with the TypeScript reference impl's output.
    """
    private_key = Ed25519PrivateKey.generate()
    private_pem = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption(),
    )
    public_pem = private_key.public_key().public_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    return private_pem, public_pem


def load_private_key(pem: Union[bytes, str]) -> Ed25519PrivateKey:
    """Load an ed25519 private key from PKCS#8 PEM bytes or str."""
    pem_bytes = pem.encode("utf-8") if isinstance(pem, str) else pem
    key = serialization.load_pem_private_key(pem_bytes, password=None)
    if not isinstance(key, Ed25519PrivateKey):
        raise ValueError("key is not an ed25519 private key")
    return key


def load_public_key(pem: Union[bytes, str]) -> Ed25519PublicKey:
    """Load an ed25519 public key from SPKI PEM bytes or str."""
    pem_bytes = pem.encode("utf-8") if isinstance(pem, str) else pem
    key = serialization.load_pem_public_key(pem_bytes)
    if not isinstance(key, Ed25519PublicKey):
        raise ValueError("key is not an ed25519 public key")
    return key


def sign_record(record: AuditRecord, private_key: Ed25519PrivateKey) -> str:
    """Sign a record's canonical bytes. Returns `ed25519:<base64url>`.

    Canonical bytes are produced by `canonicalize_for_hash`, which strips the
    `signature` field — so it is safe to pass a record whose signature is
    `None` or already set; either way the same canonical bytes are signed.
    """
    canonical = canonicalize_for_hash(record)
    sig_bytes = private_key.sign(canonical)
    return SIGNATURE_PREFIX + _b64url_encode(sig_bytes)


def verify_record(record: AuditRecord, public_key: Ed25519PublicKey) -> bool:
    """Return True iff record.signature matches the canonical bytes under key.

    Records with a missing, null, non-string, or malformed signature return
    False — callers decide whether to allow unsigned records (typically only
    at compatibility boundaries).
    """
    sig = record.get("signature")
    if not isinstance(sig, str) or not sig.startswith(SIGNATURE_PREFIX):
        return False
    sig_b64 = sig[len(SIGNATURE_PREFIX) :]
    try:
        sig_bytes = _b64url_decode(sig_b64)
    except ValueError:
        return False
    canonical = canonicalize_for_hash(record)
    try:
        public_key.verify(sig_bytes, canonical)
        return True
    except InvalidSignature:
        return False


def _b64url_encode(data: bytes) -> str:
    """base64url WITHOUT padding (matches the TS impl)."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _b64url_decode(s: str) -> bytes:
    """Decode base64url without padding. Raises ValueError on invalid input."""
    # Validate alphabet — base64.urlsafe_b64decode is otherwise permissive.
    if not all(c.isalnum() or c in "-_" for c in s):
        raise ValueError("invalid base64url characters")
    padding = "=" * (-len(s) % 4)
    return base64.urlsafe_b64decode(s + padding)
